import Foundation
import AppKit
import Combine

/// One entry in clipboard history.
struct ClipItem: Identifiable, Codable, Hashable {
    var id: UUID = UUID()
    var text: String
    var copiedAt: Date = Date()
    /// Name of the app that was frontmost when the text was copied.
    var sourceApp: String?

    /// Single-line preview for menus and the picker.
    func preview(maxLength: Int = 80) -> String {
        let collapsed = text
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .components(separatedBy: .newlines)
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
            .joined(separator: " ⏎ ")
        if collapsed.count <= maxLength { return collapsed }
        return String(collapsed.prefix(maxLength)) + "…"
    }
}

/// Global shortcut that opens the clipboard history picker.
enum ClipboardHotKey: String, CaseIterable, Identifiable {
    case shiftCmdV   // Flycut's default
    case optionCmdV
    case ctrlCmdV
    case off

    var id: String { rawValue }

    var label: String {
        switch self {
        case .shiftCmdV:  return "⇧⌘V"
        case .optionCmdV: return "⌥⌘V"
        case .ctrlCmdV:   return "⌃⌘V"
        case .off:        return "Off"
        }
    }
}

/// Watches the system clipboard. Two independent features hang off it:
/// - **Link cleaning**: a copied lone URL has its tracking stripped in place.
/// - **Clipboard history** (Flycut-style): text copies are kept in a list you
///   can paste back from with a global shortcut or the menu bar.
///
/// History lives in `~/Library/Application Support/Snippy/clipboard-history.json`,
/// never in the (possibly cloud-synced) library folder, and never leaves the Mac.
@MainActor
final class ClipboardManager: ObservableObject {
    @Published private(set) var items: [ClipItem] = []

    @Published var cleanLinks: Bool {
        didSet { defaults.set(cleanLinks, forKey: Keys.cleanLinks) }
    }
    @Published var historyEnabled: Bool {
        didSet {
            defaults.set(historyEnabled, forKey: Keys.historyEnabled)
            if !historyEnabled { clearHistory() }
            updateHotKey()
        }
    }
    @Published var historyLimit: Int {
        didSet {
            defaults.set(historyLimit, forKey: Keys.historyLimit)
            trimToLimit()
            scheduleSave()
        }
    }
    @Published var rememberAcrossRestarts: Bool {
        didSet {
            defaults.set(rememberAcrossRestarts, forKey: Keys.remember)
            if rememberAcrossRestarts { scheduleSave() } else { deleteSavedHistory() }
        }
    }
    @Published var hotKey: ClipboardHotKey {
        didSet {
            defaults.set(hotKey.rawValue, forKey: Keys.hotKey)
            updateHotKey()
        }
    }

    static let limitOptions = [25, 50, 100, 250, 500]

    private enum Keys {
        static let cleanLinks = "snippy.clipboard.cleanLinks"
        static let historyEnabled = "snippy.clipboard.historyEnabled"
        static let historyLimit = "snippy.clipboard.historyLimit"
        static let remember = "snippy.clipboard.rememberAcrossRestarts"
        static let hotKey = "snippy.clipboard.hotKey"
    }

    /// Pasteboard types that mean "don't record this": password managers,
    /// Snippy's own temporary writes, and other apps' transient data.
    private static let skipTypes: Set<NSPasteboard.PasteboardType> = [
        .snippyInternal, .transient, .concealed, .autoGenerated,
    ]
    /// Very large copies (logs, whole documents) aren't worth keeping.
    private static let maxItemLength = 100_000
    private static let pollInterval: TimeInterval = 0.4

    private let defaults = UserDefaults.standard
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private var saveWorkItem: DispatchWorkItem?
    private var globalHotKey: GlobalHotKey?
    private lazy var picker = ClipboardPickerController(manager: self)

    init() {
        // Stored properties can't be read before they're all initialized, so use locals.
        let defaults = UserDefaults.standard
        defaults.register(defaults: [
            Keys.cleanLinks: true,
            Keys.historyEnabled: true,
            Keys.historyLimit: 100,
            Keys.remember: true,
            Keys.hotKey: ClipboardHotKey.shiftCmdV.rawValue,
        ])
        cleanLinks = defaults.bool(forKey: Keys.cleanLinks)
        historyEnabled = defaults.bool(forKey: Keys.historyEnabled)
        historyLimit = defaults.integer(forKey: Keys.historyLimit)
        rememberAcrossRestarts = defaults.bool(forKey: Keys.remember)
        hotKey = ClipboardHotKey(rawValue: defaults.string(forKey: Keys.hotKey) ?? "") ?? .shiftCmdV
        lastChangeCount = NSPasteboard.general.changeCount

        if historyEnabled && rememberAcrossRestarts { loadHistory() }
        updateHotKey()
        startPolling()
    }

    // MARK: - Polling

    private func startPolling() {
        let timer = Timer(timeInterval: Self.pollInterval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        // .common so polling keeps running while a menu is open.
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func poll() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count

        let types = Set(pasteboard.types ?? [])
        guard types.isDisjoint(with: Self.skipTypes),
              var text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return }

        if cleanLinks, let cleaned = URLCleaner.clean(text) {
            // Only a lone URL gets here, so replacing the whole clipboard with
            // the clean link loses nothing the user meant to copy.
            pasteboard.clearContents()
            pasteboard.setString(cleaned, forType: .string)
            pasteboard.setString(cleaned, forType: .URL)
            lastChangeCount = pasteboard.changeCount
            text = cleaned
        }

        if historyEnabled && text.count <= Self.maxItemLength {
            record(text, sourceApp: NSWorkspace.shared.frontmostApplication?.localizedName)
        }
    }

    // MARK: - History

    private func record(_ text: String, sourceApp: String?) {
        items.removeAll { $0.text == text }
        items.insert(ClipItem(text: text, sourceApp: sourceApp), at: 0)
        trimToLimit()
        scheduleSave()
    }

    private func trimToLimit() {
        if items.count > historyLimit {
            items.removeLast(items.count - historyLimit)
        }
    }

    func delete(_ item: ClipItem) {
        items.removeAll { $0.id == item.id }
        scheduleSave()
    }

    func clearHistory() {
        items.removeAll()
        scheduleSave()
    }

    /// Put `item` on the clipboard, move it to the top of history, and paste it
    /// into the frontmost app.
    func paste(_ item: ClipItem) {
        pasteboard.clearContents()
        pasteboard.setString(item.text, forType: .string)
        lastChangeCount = pasteboard.changeCount
        record(item.text, sourceApp: item.sourceApp)
        // Give the picker/menu time to close so focus is back in the target app.
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.08) {
            SyntheticKeys.pasteCommand()
        }
    }

    func showPicker() {
        guard historyEnabled else { return }
        picker.toggle()
    }

    private func updateHotKey() {
        globalHotKey = nil
        guard historyEnabled, hotKey != .off else { return }
        globalHotKey = GlobalHotKey(preset: hotKey) { [weak self] in
            self?.showPicker()
        }
    }

    // MARK: - Persistence

    private var historyFileURL: URL {
        FileManager.default
            .urls(for: .applicationSupportDirectory, in: .userDomainMask)
            .first!
            .appendingPathComponent("Snippy", isDirectory: true)
            .appendingPathComponent("clipboard-history.json")
    }

    private func loadHistory() {
        guard let data = try? Data(contentsOf: historyFileURL) else { return }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        if let saved = try? decoder.decode([ClipItem].self, from: data) {
            items = saved
            trimToLimit()
        }
    }

    private func scheduleSave() {
        guard rememberAcrossRestarts else { return }
        saveWorkItem?.cancel()
        let item = DispatchWorkItem { [weak self] in
            MainActor.assumeIsolated { self?.saveNow() }
        }
        saveWorkItem = item
        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0, execute: item)
    }

    private func saveNow() {
        let url = historyFileURL
        do {
            try FileManager.default.createDirectory(at: url.deletingLastPathComponent(),
                                                    withIntermediateDirectories: true)
            let encoder = JSONEncoder()
            encoder.dateEncodingStrategy = .iso8601
            let data = try encoder.encode(items)
            try data.write(to: url, options: .atomic)
            // Clipboard contents can be sensitive: owner read/write only.
            try FileManager.default.setAttributes([.posixPermissions: 0o600],
                                                  ofItemAtPath: url.path)
        } catch {
            NSLog("Snippy: failed to save clipboard history: \(error)")
        }
    }

    private func deleteSavedHistory() {
        saveWorkItem?.cancel()
        try? FileManager.default.removeItem(at: historyFileURL)
    }
}
