import Foundation
import AppKit
import Carbon.HIToolbox

/// Posts synthetic keystrokes to the frontmost app.
enum SyntheticKeys {
    static func pasteCommand() {
        let source = CGEventSource(stateID: .combinedSessionState)
        let down = CGEvent(keyboardEventSource: source,
                           virtualKey: CGKeyCode(kVK_ANSI_V),
                           keyDown: true)
        down?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)
        let up = CGEvent(keyboardEventSource: source,
                         virtualKey: CGKeyCode(kVK_ANSI_V),
                         keyDown: false)
        up?.flags = .maskCommand
        up?.post(tap: .cghidEventTap)
    }
}

extension NSPasteboard.PasteboardType {
    /// Marks pasteboard writes Snippy makes for its own mechanics (snippet paste,
    /// clipboard restore) so clipboard history doesn't record them.
    static let snippyInternal = NSPasteboard.PasteboardType("au.com.getlever.snippy.internal")
    /// nspasteboard.org conventions, honoured by clipboard managers.
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
}
